workflows:
  android-workflow:
    name: Android Debug APK
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - name: Grant execute permission for gradlew
        script: chmod +x ./gradlew || true

      - name: Build debug APK
        script: |
          if [ -f "./gradlew" ]; then
            ./gradlew assembleDebug
          else
            gradle assembleDebug
          fi
    artifacts:
      - app/build/outputs/**/*.apk
